accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

colorize/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "colorizes"

urlpatterns = [
    path('index', views.index, name = "index"),
    path('upload/', views.upload,name = "upload"),
    path('upload2/', views.upload2,name = "upload2"),
    path('colorize/',views.colorize,name="colorize"),
    # path('search/', views.search, name = "search")
]

community/urls.py
from django.urls import path
from . import views

app_name ="community"

urlpatterns = [
    path('', views.index, name="index"),
    path('communityMain/', views.communityMain, name="communityMain"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yolos/', include('yolos.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('colorize/', include('colorize.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolos/urls.py
from django.urls import path
from . import views

app_name = "yolos"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('upload/', views.upload, name="upload"),
    path('goflow/', views.goflow, name="goflow"),
]

mysite/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap');    </style>
  <style>
      #card-result {
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: 'Black Han Sans', sans-serif;
  }

    body {
      font-family: 'Noto Sans KR', sans-serif !important;
    }
  </style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/568bce6e29.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  {% bootstrap_css %}

  <title>Document</title>
  
  
  <link rel="stylesheet" href="{% static 'accounts/css/common.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
  <link rel="shortcut icon" href="{% static 'accounts/imgs/ooak1.png' %}">

</head>
<body>
  <!-- 최상단  -->

  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'community:index' %}">OOAK</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
      </li>
      {% else %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">join</a>
      </li>
      {% endif %}
     
  </nav>
  <!-- 메뉴 -->
  <nav class="navbar" style="background-color: #e3f2fd;">
    <nav class="nav nav-pills flex-column flex-sm-row">
      <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'community:communityMain' %}">Community</a>
      <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'colorizes:index' %}">Customizing</a>
      <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'yolos:search' %}">YoLo</a>  
    </nav>
  </nav>
  <hr>
  {% block body %}
  {% endblock %}

  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message.message }}
    </div>
  {% endfor %}
  {% endif %}   

  {% bootstrap_javascript jquery='full' %}
</body>
</html>