accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

community/urls.py
from django.urls import path
from . import views

app_name ="community"

urlpatterns = [
    path('', views.index, name="index"),
    path('communityMain/', views.communityMain, name="communityMain"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yolos/', include('yolos.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('colorize/', include('colorize.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolos/urls.py
from django.urls import path
from . import views

app_name = "yolos"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('upload/', views.upload, name="upload"),
    path('goflow/', views.goflow, name="goflow"),
]

community/models.py
# from django.db import models

# # Create your models here.

# class Article(models.Model) : 
#     title = models.CharField(max_length=150)
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
    
#     def __str__(self):
#         return f'Article:{self.pk}번째 글, {self.title}-{self.content}'

from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
def articles_image_path(instance, filename):
    return 'user_{a}/{b}'.format(instance.user.pk,filename)

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank = 유효성 검사시
    # null = DB 상의 컬럼의 Null
    image = models.ImageField(blank=True, upload_to=articles_image_path)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality':90}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hits=models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles',
        blank=True
    )
    recommend_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='recommend_articles',
        blank=True
    )

    @property
    def click(self):
        self.hits+=1
        self.save()

    # def __str__(self):
    #     return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name='comments'
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # def __str__(self):
    #     return f'Article:{self.article}, {self.pk}-{self.content}'

community/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ['user', 'like_users','recommend_users', 'hits']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields= '__all__'
        exclude = ['article', 'user']

community/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from community.models import Article, Comment
from .forms import ArticleForm, CommentForm


# Create your views here.

def index(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {
        'articles': articles
    }
    return render(request, 'community/index.html', context)


def communityMain(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'community/communityMain.html', context)


def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, "게시글 작성 완료!")
            return redirect('community:communityMain')
        else:
            messages.error(request, "똑바로 써")
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'community/create.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    article.click
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'community/detail.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('community:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form
        }
        return render(request, 'community/create.html', context)
    else:
        return redirect('community:detail', article.pk)

@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
            return redirect('community:index')
        else:
            return redirect('community:detail', article.pk)
    return redirect('accounts:login')

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
            return redirect('community:detail', article.pk)
        else:
            context = {
                'comment_form': comment_form,
                'article': article
            }
            return render(request, 'community/index.html', context)
    else:
        return redirect('accounts:login')
    

@require_POST
def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
        return redirect('community:detail', article_pk)
    else:
        return redirect('accounts:login')

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if user in article.like_users.all():
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True
    context = {
        'liked': liked,
        'count': article.like_users.count()
    }
    return JsonResponse(context)

@login_required
def recommend(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if user in article.recommend_users.all():
        article.recommend_users.remove(user)
    else:
        article.recommend_users.add(user)
    return redirect('community:index')

community/templates/community/_like.html
<p class="card-text">
  <!-- Like -->
  {% if user in article.like_users.all %}
  
    <i class="fas fa-heart fa-lg like-button" data-id="{{ article.pk }}" style="color: crimson;"></i>
  {% else %}
    <i class="far fa-heart fa-lg like-button" data-id="{{ article.pk }}" style="color: black;"></i>
  {% endif %}
  <span id="like-count-{{ article.pk }}">{{ article.like_users.count }}</span>
</p>
<hr>

community/templates/community/communityMain.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
  <div class="container">
    <h1>community 페이지</h1> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th>번호</th>
          <th>제목</th>
          <th>작성자</th>
          <th>작성일</th>
          <th>조회수</th>
          <th>좋아요</th>
        </tr>
      </thead>  
      <tbody>
        {% for article in articles %}
        <tr>
          <td scope="row">{{article.pk}}</td>
          <td><a href="{% url 'community:detail' article.pk %}">{{article.title}}</a>
          [{{article.comment_set.all|length}}]
          </td>
          <td>{{ article.user }}</td>
          <td>{{article.created_at}}</td>
          <td>{{ article.hits }}</td>
          <td>{{ article.like_users.count }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <hr/>
    <a class="btn btn-primary pull-left" href="{% url 'community:create' %}">글쓰기</a>
  </div> 
{% endblock %}

community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container">
  {% if request.resolver_match.url_name == 'create' %}
    <h1>글 생성</h1>
  {% else %}
    <h1>글 수정</h1>
  {% endif %}

  <hr>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    {% endbuttons %}
  </form>
    <a href="{% url 'community:index' %}">[BACK]</a>
</div>
{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block body %}
<div class="container">
  <h1>상세 페이지</h1>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th>제목</th>
          <td colspan="16">{{ article.title }}</td>
      </tr>
      <tr>
        <th>작성자</th>
          <td colspan="6">{{ article.user }}</td>
        <th>작성일</th>
            <td colspan="2">{{ article.created_at }}</td>
        <th>조회</th>
          <td colspan="2">{{ article.hits }}</td>
        <th>추천</th>
          <td colspan="2">{{ article.like_users.count }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
  <table class="table table-borderless">
    <tbody>
      <p>{{ article.content }}</p>
      {% if article.image %}
      <p><img src="{{ article.image.url }}" alt="{{ article.image }}"></p> 
      {% endif %}
    </tbody>
  </table>
{% include 'community/_like.html' %}
<ul>
  {% for comment in comments %}
    <table class="table table-striped">
        <tbody>
          <tr>
            <td>{{ comment.user.username }}</td>
            <td class="text-right">{{ comment.created_at }}</td>
          </tr>
          <tr>
            <td>{{ comment.content }}</td>
          </tr>
        </tbody>     
    </table>
    {% if request.user == comment.user %}
      <form action="{% url 'community:comment_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="댓글 삭제" class="btn btn-outline-light">
      </form>
    {% endif %}

  {% empty %}
    <p>댓글이 없습니다.</p>  
  {% endfor %}
</ul>
<hr>
{% if user.is_authenticated %}
  <form action="{% url 'community:comment_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="댓글생성" class="btn btn-outline-primary">
  </form>
{% else %}
  <a href="{% url 'accounts:login' %}">[댓글을 작성하시려면 로그인을 해 주세요.]</a>
{% endif %}
<hr>
{% if request.user == article.user %}
  <a class="btn btn-primary" href="{% url 'community:communityMain' %}">목록</a>
  <a class="btn btn-primary" href="{% url 'community:update' article.pk %}">수정하기</a>
  <form action="{% url 'community:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-outline-light">
  </form>
{% else %}
  <a href="{% url 'community:index' %}">[back]</a>
{% endif %}

</div> 
<script src="{% static 'articles/js/like.js' %}"></script>
{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="row justify-content-center">
  {% for article in articles %}
    <div class="card col-3 m-3" style="width: 18rem;">
      <!-- Card Image -->
      {% if article.image %}
        <img src="{{ article.image_thumbnail.url }}" class="card-img-top" alt="{{ article.image }}" style="height: 10rem;">
      {% else %}
        <img src="{% static 'articles/images/noimage.jpeg' %}" class="card-img-top" alt="이미지 없음">
      {% endif %}
      
      <!-- Card Body -->
      <div class="card-body">
        <!-- Card Title -->
        <a href="{% url 'articles:detail' article.pk %}"><h5 class="card-title btn-outline-light text-dark">{{ article.title }}</h5></a>
        <hr>
        <!-- Article User -->
        <p>작성자 : {{ article.user.username }}</p>

        {% include 'community/_like.html' %}

      </div>
    </div>
  {% endfor %}
  
</div>
{% endblock %}