accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yolos/', include('yolos.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('colorize/', include('colorize.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolos/urls.py
from django.urls import path
from . import views

app_name = "yolos"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('upload/', views.upload, name="upload"),
    path('goflow/', views.goflow, name="goflow"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="followings",
        blank=True
    )

accounts/templates/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="followings",
        blank=True
    )

community/models.py
# from django.db import models

# # Create your models here.

# class Article(models.Model) : 
#     title = models.CharField(max_length=150)
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
    
#     def __str__(self):
#         return f'Article:{self.pk}번째 글, {self.title}-{self.content}'

from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
def articles_image_path(instance, filename):
    return 'user_{a}/{b}'.format(instance.user.pk,filename)

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank = 유효성 검사시
    # null = DB 상의 컬럼의 Null
    image = models.ImageField(blank=True, upload_to=articles_image_path)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality':90}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hits=models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles',
        blank=True
    )
    recommend_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='recommend_articles',
        blank=True
    )

    @property
    def click(self):
        self.hits+=1
        self.save()

    # def __str__(self):
    #     return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name='comments'
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # def __str__(self):
    #     return f'Article:{self.article}, {self.pk}-{self.content}'

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        

accounts/templates/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:communityMain')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:communityMain')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:communityMain')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('community:communityMain')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('community:communityMain')

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            return redirect('community:communityMain')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('community:communityMain')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('accounts:profile', person.username )

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="비밀번호 수정">
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
<section id="container">
    <div id="main_container">
        <div class="form_container">
            <div class="form">
                <h1 class="sprite_insta_big_logo title"></h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" id="submit_btn" value="로그인" class="submit_btn">
                </form>
            </div>
            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="{% url 'accounts:signup' %}">회원가입</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
</html>

accounts/templates/accounts/login3.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class="container">
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="로그인">
  </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<h1>{{ person.username }}</h1>
<!-- 팔로우 로직 구현 -->
{% if user != person %}
  {% if user in person.followers.all %}
    <a href="{% url 'accounts:follow' person.pk %}">팔로우 취소</a>
  {% else %}
    <a href="{% url 'accounts:follow' person.pk %}">팔로우</a>
  {% endif %}
{% endif %}

<!-- 유저가 작성한 모든 게시물 -->
<p>유저가 작성한 게시글들</p>
<ul>
  {% for article in person.article_set.all %}
    <li>{{ article.title }}</li>
    <li>{{ article.content }}</li>
  {% endfor %}
</ul>

<!-- 유저가 작성한 모든 댓글 -->
<p>유저가 작성한 댓글들</p>
<ul>
  {% for comment in person.comment_set.all %}
    <li>{{ comment.content }}</li>
  {% empty %}
    <p>댓글을 단 적이 없습니다.</p>
  {% endfor %}
</ul>

<!-- 유저가 좋아요 누른 게시글 -->
<p>유저가 좋아요 누른 게시글</p>
<ul>
  {% for like in person.like_articles.all %}
    <li>{{ like.content }}</li>
  {% empty %}
    <p>좋아요를 누른 적이 없습니다.</p>
  {% endfor %}
</ul>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<section id="container">
  <div id="main_container">
    <div class="form_container">
      <div class="form">
        <h1 class="sprite_insta_big_logo title"></h1>
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="회원가입" class="submit_btn">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block body %}
<h1>회원 정보 수정 페이지</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="회원수정">
</form>
{% endblock %}