mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yolos/', include('yolos.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('colorize/', include('colorize.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolos/urls.py
from django.urls import path
from . import views

app_name = "yolos"

urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('upload/', views.upload, name="upload"),
    path('goflow/', views.goflow, name="goflow"),
]

yolos/models.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class Search(models.Model):
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
        # source='image',
        processors=[Thumbnail(500,500)],
        format='JPEG',
        options={'quality':90}
    )

yolos/forms.py
from django import forms
from .models import Search

class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = ['image']

yolos/views.py
from django.shortcuts import render, redirect
from .models import Search
from .forms import SearchForm
from django.http import JsonResponse
from .darkflow.darkflow.net.build import TFNet
import cv2
import os
import json
from django.conf import settings
import numpy as np

# Create your views here.
def index(request):
    return render(request, 'yolos/index.html')

def search(request):
    # search = Search.objects.all()
    # upimg = search[0].image
    # context = {
    #     'upimg': upimg
    # }
    return render(request, 'yolos/search.html')

def upload(request):
    _, files = request.FILES.popitem()
    files = files[0]
    search = Search()
    search.image = files
    search.save()
    img = Search.objects.all().last()
    # print(img.url)
    print(img.image.url)
    print(img.image.name)
    context = {
        'img_url': img.image.url,
        'img_name': img.image.name,
    }
    return JsonResponse(context)

def goflow(request):
    search = Search()
    img = Search.objects.all().last()
    module_dir = os.path.dirname(__file__)
    file_path = os.path.join(module_dir, 'darkflow', 'cfg', 'my-tiny-yolo.cfg')
    print(module_dir)
    print(file_path)
    options = {
        "model": file_path,
        "load": -1,
        "threshold": 0.1
    }
    print('==')
    tfnet = TFNet(options)
    print('===')
    path = os.path.join(settings.BASE_DIR, settings.MEDIA_ROOT, img.image.name)
    print(path)
    # print(path)
    imgcv = cv2.imread(path)
    # print(imgcv)
    result = tfnet.return_predict(imgcv)
    print(type(result))
    reimg = json.dumps(str(result[0]))
    print(reimg)
    print('-------------')
    b = imgcv.tolist()
    a = json.dumps(b)
    for r in result:
        r['confidence'] = str(r['confidence'])
    context = {
        'result': result,
        'img_url': img.image.url,
    }
    return JsonResponse(context)

yolos/templates/yolos/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
  <h1>yolo</h1>
  <img src="{% static 'yolos/images/aa.png' %}" alt="">
  <a href="{% url 'yolos:search' %}">검색하기</a>
{% endblock %}

yolos/templates/yolos/search.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block css %}
<style>
  #card-result {
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: 'Black Han Sans', sans-serif;
  }

</style>

{% endblock %}

{% block body %}
{% load static %}

<h1>신발, 너 이름이 뭐니??</h1>

<hr>
<!-- <img src="{% static 'yolos/images/aa.png' %}" alt="" id="imgSrc">
<br>
<input type="file" id="file" name="file">
<input type=submit value=Upload id="upload">
<br>
<input type=submit value="확인" id="yolo"> -->
<!-- <div id="result-image-div" style="position: relative;">
  <img src="{% static 'yolos/images/aa.png' %}" alt="" id="resultImg">
  <div class="label"></div>
</div>
<div id="result"></div> -->

<div class="row" style="">
  <div class="col-6" style="height: 500px;">
    <div class="card"  style="height: 500px;" >
      <div  style="height: 500px;"class="card-body d-flex justify-content-center d-flex align-itmes-center justify-content-center flex-column">
        <h3 class="card-title text-center" id="name">신발 검색</h3>
        <hr class="mb-5 border border-primary" style="width: 5rem;">
        <p class="card-text" id="per">
          <ol>
            <li>이름을 알고 싶은 신발 사진을 업로드</li>
            <li>확인 버튼을 누르면 끝</li>
          </ol>
        </p>
        <div class="text-center">
          <p class="text-center">원하는 사진을 선택해 주세요.</p>
          <input type="file" id="fileupload" name="file" accept="image/*">
          <!-- <p>신발 확인하기</p> -->
        </div>
      </div>
    </div>
  </div>
<div class="col-6" style="max-height: 500px; line-height: 500px;">
  <img src="{% static 'yolos/images/aa.png' %}" alt="" id="imgSrc" class="card-img-top">
</div>
</div>
<div class="my-5 text-center">
  <input type=submit value="결과 확인" id="yolo" class="btn btn-primary btn-lg">
</div>
  <div class="">

    <div class="card" style="display: none;" id="resultCard">
      <div class="row no-gutters">
        <div class="col-md-6 d-flex justify-content-center d-flex align-itmes-center justify-content-center flex-column">
          <div id="result-image-div" style="position: relative;">
            <img src="{% static 'yolos/images/aa.png' %}" alt="" id="resultImg" class="">
            <div class="label"></div>
          </div>
        </div>
        <div class="col-md-6" id="card-result">
          <div class="card-body">
            <!-- <h5 class="card-title">Card title</h5> -->
            <!-- <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> -->
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
            <div id="result"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

<a href="{% url 'yolos:index' %}">[BACK]</a>

<script src="{% static 'yolos/js/upload.js' %}"></script>
{% endblock %}